language: cpp
sudo: false
dist: trusty
compiler:
  - g++
os:
  - linux

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

branches:
  only:
   - master

script: ./build.sh

notifications:
  email:
    - mebenstein@student.tgm.ac.at

env:
  global:
<<<<<<< HEAD:.travis.yaml
    - LANG="en_US.UTF-8"
=======
- LANG="en_US.UTF-8"
>>>>>>> 52ad10f6248ae2ba5ad516444e7ff20d88fc4f6f:.travis.yml
